version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django_admin_db
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: django_post_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server:latest
    platform: linux/amd64
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  postgres_data:
  clickhouse_data: