version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django_admin_db
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: django_post_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - clickhouse
      - kafka

  clickhouse:
    image: yandex/clickhouse-server:latest
    platform: linux/amd64
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_integration:
    build:
      context: ./core
      dockerfile: Dockerfile
    volumes:
      - ./core:/app
    command: python kafka_integration/producer.py
    depends_on:
      - kafka

volumes:
  postgres_data:
  clickhouse_data: