# Generated by Django 3.2.12 on 2024-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240617_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHouseUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'users_table',
                'managed': False,
            },
        ),
    ]
